#!/usr/bin/env bash
# transfers a file from our client to a server

if [ $# -lt 4 ]
then
    echo " Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# disabling strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$4:~/"

# checking if the transfer was successful
if [ &? -eq 0 ]
then
    echo "file transfer was successfully made"
else
    echp "file transfeer failed"
fi
