#!/usr/bin/env bash
# commands to Install nginx web server

# first check updates and then install nginx and make listen to the port 80
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

# 
echo "Hello World!" | sudo tee /var/www/html/index.html

# test the nginx configurations
sudo nginx -t

# reload the nginx server
service nginx start
