#!/usr/bin/env bash
# commands to Install nginx web server


sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
 
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo nginx -t
service nginx reload
