#!/usr/bin/env bash
# printing Best School 10 times using while loop 
# in the 9th loop print Hi

i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
        echo "Best School"
    else
        echo "Hi"
    fi
    ((i++))
done
