#!/usr/bin/env bash
#script that gives information about the school file

var="school"

if [ -e $var ]
then
    echo "school file exists"
    if [ -f $var ]
    then
        echo "school file is not empty"
    elif [ -s $var ]
    then
        echo "school is a regular file"
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
